apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: cc-movimientos-ms-namespace
spec:
  dnsNames:
    - portalbancario.alquinta.xyz
  secretName: tls-secret-key
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer