apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cc-movimientos-ms-ingress
  namespace: cc-movimientos-ms-namespace
spec:
  tls:
    - hosts:
      - portalbancario.alquinta.xyz
      secretName: tls-secret-key
  ingressClassName: nginx
  rules:
    - host: portalbancario.alquinta.xyz
      http:
        paths:
          - path: /cc-movimientos
            pathType: Prefix
            backend:
              service:
                name: cc-movimientos-ms-svc
                port:
                  number: 80