apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: movimientos-ms-hpa
  namespace: movimientos-ms-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movimientos-ms
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
